package models;

public enum Endpoint {
    GET_PRIORITIZED,
    GET_TASK,
    GET_EPIC,
    GET_SUB,
    GET_HISTORY,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUB,
    GET_TASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_SUB_BY_ID,
    DELETE_TASK_BY_ID,
    DELETE_EPIC_BY_ID,
    DELETE_SUB_BY_ID,
    POST_TASK,
    POST_EPIC,
    POST_SUB,
    GET_EPIC_SUB,
    UNKNOWN
}
